version: '2.3'

x-environment: &environment
  DEBUG: 1

services:
  emb:
    container_name: embedder
    image: ghcr.io/huggingface/text-embeddings-inference:1.5.1
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./models/nlp/embedders:/data
    pull_policy: never
    environment:
      <<: *environment
    command: --model-id intfloat/multilingual-e5-large-instruct --max-client-batch-size 512 --max-concurrent-requests 512
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ '0' ]
            capabilities: [gpu]
    shm_size: 64g
    ulimits:
      memlock: -1
      stack: 67108864
      
  reranker:
    container_name: reranker
    image: ghcr.io/huggingface/text-embeddings-inference:1.5.1
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./models/nlp/rerankers:/data
    pull_policy: never
    environment:
      <<: *environment
    command: --model-id BAAI/bge-reranker-v2-m3 --max-client-batch-size 128 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ '0' ]
            capabilities: [gpu]
    shm_size: 64g
    ulimits:
      memlock: -1
      stack: 67108864
      
  vllm:
    container_name: vllm
    image: vllm/vllm-openai:latest
    restart: always
    ports:
      - 8071:8000
    volumes:
      - ./models/nlp/llm:/models
    environment:
      <<: *environment
    command: --model /models/Qwen2.5-7B-Instruct-GPTQ-Int4 --port 8000 --served-model-name Qwen/Qwen2.5-7B-Instruct-GPTQ-Int4 --enable-auto-tool-choice --tool-call-parser hermes --gpu-memory-utilization 0.85
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ '0' ]
            capabilities: [gpu]
    shm_size: 64g
    ulimits:
      memlock: -1
      stack: 67108864

  etcd:
    container_name: milvus-etcd
    restart: always
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volume_extra_services/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  minio:
    container_name: milvus-minio
    restart: always
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    expose:
      - 9001
    volumes:
      - ./volume_extra_services/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    ports:
      - 9001:9001
      - 9000:9000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  milvus-standalone:
    container_name: milvus-standalone
    restart: always
    image: milvusdb/milvus:v2.4.11
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./volume_extra_services/milvus:/var/lib/milvus
    ports:
      - 19530:19530
    depends_on:
      - "etcd"
      - "minio"