# --------------------------------------------- HYDRA -----------------------------------------------------
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:  
    dir: .

# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  save_parsing_results_to_file: False  # Сохранение текста и чанков в файл для дебага

# ------------------------------------------------- NODES --------------------------------------------------

DataParsingNode:
  min_words: 3 # минимальное число слов в предложении

chunking_node:
  chunk_size: 1500  # максимальный размер чанка в символах
  chunk_overlap: 0 # перекрытие между чанками в символах

vector_db_node:  
  host: localhost
  port: 19530

embedder_node:
  host: localhost
  port: 8080
  top_k: 20 # сколько сообщений взять ближайших чанков из бд

reranker_node:
  host: localhost
  port: 8081
  top_k: 5 # сколько ближайших значений после реранка в итоговый запрос
  min_score: 0.005 # минимальный порог по релевантонсти для подачи в запрос

llm_node:
  host: localhost
  port: 8071
  model_name: "Qwen/Qwen2.5-7B-Instruct-GPTQ-Int4"
  temperature: 0 # Устанавливаем температуру (от 0 до 1, где 0 - детерминированный ответ, 1 - более случайный)
  max_tokens: 5000  # ограничивает количество токенов в ответе


