# ------------------------------------------------- NODES --------------------------------------------------

data_parsing_node:
  min_words: 4 # минимальное число слов в предложении

chunking_node:
  chunk_size: 1250  # максимальный размер чанка в символах
  chunk_overlap: 0 # перекрытие между чанками в символах

vector_db_node:  
  host: localhost
  port: 19530
  dim: 1024 # размерность вектора
  top_k: 20 # сколько сообщений взять ближайших чанков из бд

embedder_node:
  host: localhost
  port: 8080
  max_batch_size: 512 # сколько чанков можно подать за раз

reranker_node:
  host: localhost
  port: 8081
  top_k: 5 # сколько ближайших значений после реранка в итоговый запрос
  min_score: 0.005 # минимальный порог по релевантонсти для подачи в запрос

llm_node:
  host: localhost
  port: 8071
  model_name: "Qwen/Qwen2.5-7B-Instruct-GPTQ-Int4"
  temperature: 0 # Устанавливаем температуру (от 0 до 1, где 0 - детерминированный ответ, 1 - более случайный)
  max_tokens: 5000  # ограничивает количество токенов в ответе


